- hosts: servidores
  become: true
  tasks:
    - name: "Comprobamos si tiene conectividad"
      ping:
    # Actualizamos los paquetes 
    - name: "Actualizar el sistema"
      apt: update_cache=yes upgrade=yes
    # Instalar un paquete
    - name: "Instalar Git"
      apt:
        name: git
    # Copiar un fichero al servidor remoto"
    - name: "Copiar fichero"
      copy:
        src: Files/prueba.txt
        dest: /home/ansible/
        owner: root
        group: root
        mode: '0644'